server:
  port: 9001

spring:
  application:
    name: elo-engine
  datasource:
    username: xxx
    url: jdbc:postgresql://localhost:5432/postgres
    password: xxx
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'